<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "navsoapinterface"
 *
 * Auto generated by Extension Builder 2014-02-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'NAV Web Services - SOAP-Interface',
	'description' => 'connect to a soap interface',
	'category' => 'plugin',
	'author' => 'Berti Golf',
	'author_email' => 'berti.golf@blsv.de',
	'author_company' => 'BLSV',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.8.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>